baseurl = "localhost:1313"
languageCode = "en-us"
theme = "hugo-elate-theme"
title = "Elate theme"
[params]
author = ""
custom_css = ["css/custom1.css", "css/custom2.css"]
description = ""
email = "hello@dash-cloud.com"
googleMapsApiKey = ""
[params.about]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = true
title = "About"
[[params.about.item]]
alt = "Person1"
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
img = "person1.jpg"
name = "Jean Smith"
position = "Web Designer"
social = [["icon-twitter", "#"], ["icon-facebook", "#"], ["icon-linkedin", "#"]]
[[params.about.item]]
alt = "Person2"
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
img = "person2.jpg"
name = "Rob Smith"
position = "Web Developer"
social = [["icon-twitter", "#"], ["icon-facebook", "#"], ["icon-github", "#"]]
[[params.about.item]]
alt = "Person3"
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
img = "person3.jpg"
name = "Larry Ben"
position = "Web Designer"
social = [["icon-twitter", "#"], ["icon-facebook", "#"], ["icon-dribbble", "#"]]
[params.contact]
button = "Send message"
description = "Interested in partnering with us? Feel free to contact us!"
details = [["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"], ["icon-phone", "(123) 465-6789"], ["icon-envelope", "info@freehtml5.co"], ["icon-globe", "<a href=\"http://freehtml5.co/\" target=\"_blank\">freehtml5.co</a>"]]
email = "Email"
enable = true
form = true
map = true
message = "Message"
name = "Name"
phone = "Phone"
title = "Get in touch"
[params.counters]
background = "full_image_1.jpg"
enable = true
title = "Stats"
[[params.counters.item]]
description = "Finished Projects"
from = "0"
icon = "icon-briefcase"
interval = "1"
speed = 5000
to = "8"
[[params.counters.item]]
description = "Lines of code"
from = 0
icon = "icon-code"
interval = 50
speed = 5000
to = 2343409
[[params.counters.item]]
description = "Cups of coffee"
from = 0
icon = "icon-cup"
interval = 50
speed = 5000
to = 1302
[[params.counters.item]]
description = "Happy clients"
from = 0
icon = "icon-people"
interval = 50
speed = 5000
to = 52
[params.footer]
copyright = "&copy; 2020 Dash Cloud. All rights reserved."
enable = true
links = [["icon-twitter", "#twitter"], ["icon-facebook", "#facebook"], ["icon-youtube", "#youtube"]]
[params.hero]
subtitle = "Award-winning hosted cloud for high-performance-compute at a fraction of the cost. From NVIDIA 1080s to V100s, we have the hardware your HPC needs require. "
title = "Faster, Better, Cheaper — That's Dash Cloud"
[params.intro.video]
enable = false
icon = "icon-play2"
title = "NVIDIA 3080s Available"
url = "https://www.youtube.com/embed/7QeoZY4tf9I"
[[params.intro.item]]
button = "Contact Us"
description = "Rent V100s from $0.75/hour and NVIDIA 3080s from $0.40/hour! That's 50% less than competing public clouds!"
icon = "icon-money"
img = "img_7.jpg"
title = "Cheaper"
url = "#fh5co-contact"
[[params.intro.item]]
button = "Contact Us"
description = "NVMe SSDs, DDR4 RAM, Fiber optic connection. You name it, we have it. Our bleeding-edge hardware outperforms competitors. "
icon = "icon-rocket"
img = "img_8.jpg"
title = "Faster"
url = "#fh5co-contact"
[[params.intro.item]]
button = "Contact Us"
description = "Our data centers are staffed with 24x7 onsite technicians with multiple levels of security to ensure the safety of your data. "
icon = "icon-lock"
img = "img_10.jpg"
title = "Safer"
url = "#"
[params.navigation]
about = "About"
brand = "Dash Cloud"
contact = "Contact"
home = "Home"
services = "Services"
testimonials = "Testimonials"
work = "Our Work"
[params.services]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = true
title = "Services"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-anchor"
title = "Brand &amp; Strategy"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-layers2"
title = "Web &amp; Interface"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-video2"
title = "Photo &amp; Video"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-monitor"
title = "CMS &amp; eCommerce"
[params.testimonials]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = true
title = "Testimonials"
[[params.testimonials.item]]
alt = "Person1"
img = "person1.jpg"
person = "Jean Doe, CEO <a href=\"http://freehtml5.co/\" target=\"_blank\">FREEHTML5.co</a> <span class=\"subtext\">Creative Director</span>"
quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
[[params.testimonials.item]]
alt = "Person2"
img = "person2.jpg"
person = "John Doe, Senior UI <a href=\"http://freehtml5.co/\" target=\"_blank\">FREEHTML5.co</a> <span class=\"subtext\">Creative Director</span>"
quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
[[params.testimonials.item]]
alt = "Person3"
img = "person3.jpg"
person = "Chris Nash, Director <a href=\"http://freehtml5.co/\" target=\"_blank\">FREEHTML5.co</a> <span class=\"subtext\">Creative Director</span>"
quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
[params.work]
description = "Our pricing is among the most affordable in the industry. Come test us out! "
enable = true
footertext = "Contact us if you are interested!"
title = "Pricing"
[[params.work.row]]
alt = "NVIDIA 1080"
img = "zotac-1080.jpg"
subtitle = "From $0.17/hour"
title = "Cloud NVIDIA 1080s"
[[params.work.row]]
alt = "NVIDIA 3080"
img = "nvidia-3080.jpg"
subtitle = "$0.56/hour"
title = "Cloud NVIDIA 3080s"
[[params.work.row]]
alt = "NVIDIA V100"
img = "nvidia-v100.jpg"
subtitle = "From $0.84/hour"
title = "Cloud NVIDIA V100s"
